name: "Tronbyt Server"
description: "Supervisor-managed Docker add-on for ghcr.io/tronbyt/server"
version: "1.0.0"
slug: "tronbyt-server"
init: false
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386
